name: Check
on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git status
          git log --stat
