name: Hotfix
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  cherry_pick_hotfix:
    if: startsWith(github.head_ref, 'hotfix/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git fetch origin release
          git checkout release
          git cherry-pick $GITHUB_SHA
          git push
