name: Hotfix
on:
  pull_request:
    types:
      - closed
    branches:
      - main
jobs:
  cherry_pick_hotfix:
    if: startsWith(github.head_ref, 'hotfix/') && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          git log --stat
          git status
